name: Go Tests with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    env:
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Download dependencies
        run: go mod tidy

      - name: Run tests with coverage
        run: |
          go test ./... -coverprofile=coverage.out -covermode=atomic

      - name: Generate HTML coverage report
        run: |
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage report to GitHub Pages
        run: |
          mkdir -p public
          mv coverage.html public/
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
          publish_branch: gh-pages
