name: Go Tests with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    env:
      RUNNER_TOOL_CACHE: /toolcache
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures all branches are fetched for gh-pages deployment

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Download dependencies
        run: go mod tidy

      - name: Run tests with coverage
        run: |
          go test ./... -coverprofile=coverage.out -covermode=atomic

      - name: Generate HTML coverage report
        run: |
          go tool cover -html=coverage.out -o public/coverage.html

      - name: Upload Coverage Report Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public/
